In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [33]:
path = "../Data/Online_Data/trainning_data/corporate_attributes/"
outpath = "../Processed_Data/"

In [34]:
company_base_info = pd.read_csv(path+"company_base_info.csv")

In [35]:
company_base_info

,entid,honor_num,illegad_num,yea_sub,web_dum,ENTTYPE,INDUSTRYPHY,REGCAP,REGCAPCUR,RECCAP,PARNUM,LIMPARNUM,PARFORM,EXENUM,brand_num,cancel_dum,certificate_num,tax_dum
0,122697049,NaN,NaN,NaN,1,10,9,8103057.4,156.0,4700000.0,NaN,NaN,NaN,NaN,NaN,0,4.0,0
1,959830672,NaN,NaN,NaN,1,5,11,38000.0,156.0,1000.0,NaN,NaN,NaN,NaN,NaN,0,2.0,0
2,564421968,NaN,NaN,NaN,0,8,12,5000.0,156.0,5000.0,NaN,NaN,NaN,NaN,NaN,1,NaN,0
3,620868429,NaN,NaN,NaN,0,8,9,10000.0,156.0,10000.0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
4,1176966297,NaN,NaN,NaN,0,55,11,3000.0,156.0,3000.0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12274,208371641,NaN,NaN,NaN,0,65,5,20.0,156.0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
12275,331374714,NaN,NaN,NaN,0,99,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
12276,470500045,NaN,NaN,NaN,0,5,11,50.0,156.0,500.0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
12277,771018416,NaN,NaN,NaN,0,99,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
12278,1091303326,NaN,NaN,NaN,1,99,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [36]:
company_base_info["honor_num"]  = company_base_info["honor_num"].fillna(0)
company_base_info["illegad_num"]  = company_base_info["illegad_num"].fillna(0)
company_base_info["yea_sub"]  = company_base_info["yea_sub"].fillna(0)
company_base_info["REGCAP"]  = company_base_info["REGCAP"].fillna(0)
company_base_info["REGCAPCUR"]  = company_base_info["REGCAPCUR"].fillna(156)
company_base_info["RECCAP"]  = company_base_info["RECCAP"].fillna(0)
company_base_info["certificate_num"]  = company_base_info["certificate_num"].fillna(0)
company_base_info["brand_num"]  = company_base_info["brand_num"].fillna(0)

company_base_info["cap_ratio"]  = 0
company_base_info.loc[company_base_info["REGCAP"] != 0, "cap_ratio"] = company_base_info["RECCAP"]/company_base_info["REGCAP"]
company_base_info.loc[company_base_info["cap_ratio"] >= 1, "cap_ratio"] = 1

In [37]:
caec = pd.get_dummies(company_base_info["REGCAPCUR"], prefix="REGCAPCUR")
company_base_info = pd.concat([company_base_info, caec],axis=1)
company_base_info

,entid,honor_num,illegad_num,yea_sub,web_dum,ENTTYPE,INDUSTRYPHY,REGCAP,REGCAPCUR,RECCAP,...,cap_ratio,REGCAPCUR_4.0,REGCAPCUR_36.0,REGCAPCUR_156.0,REGCAPCUR_170.0,REGCAPCUR_344.0,REGCAPCUR_392.0,REGCAPCUR_840.0,REGCAPCUR_954.0,REGCAPCUR_978.0
0,122697049,0.0,0.0,0.0,1,10,9,8103057.4,156.0,4700000.0,...,0.580028,0,0,1,0,0,0,0,0,0
1,959830672,0.0,0.0,0.0,1,5,11,38000.0,156.0,1000.0,...,0.026316,0,0,1,0,0,0,0,0,0
2,564421968,0.0,0.0,0.0,0,8,12,5000.0,156.0,5000.0,...,1.000000,0,0,1,0,0,0,0,0,0
3,620868429,0.0,0.0,0.0,0,8,9,10000.0,156.0,10000.0,...,1.000000,0,0,1,0,0,0,0,0,0
4,1176966297,0.0,0.0,0.0,0,55,11,3000.0,156.0,3000.0,...,1.000000,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12274,208371641,0.0,0.0,0.0,0,65,5,20.0,156.0,0.0,...,0.000000,0,0,1,0,0,0,0,0,0
12275,331374714,0.0,0.0,0.0,0,99,19,0.0,156.0,0.0,...,0.000000,0,0,1,0,0,0,0,0,0
12276,470500045,0.0,0.0,0.0,0,5,11,50.0,156.0,500.0,...,1.000000,0,0,1,0,0,0,0,0,0
12277,771018416,0.0,0.0,0.0,0,99,19,0.0,156.0,0.0,...,0.000000,0,0,1,0,0,0,0,0,0
12278,1091303326,0.0,0.0,0.0,1,99,19,0.0,156.0,0.0,...,0.000000,0,0,1,0,0,0,0,0,0

In [38]:
dic_cur = {156.0: 1, 840.0: 6.48, 344.0: 0.83, 954.0: 7.64,       
           36.0: 0.087, 392.0: 0.059, 4.0: 9.15, 978.0: 6.48,
           170.0: 0.0017, 0: 1}
company_base_info["REGCAP_Normal"]  = company_base_info.apply(lambda row: row['REGCAP'] * dic_cur[row['REGCAPCUR']], axis = 1)
company_base_info["RECCAP_Normal"]  = company_base_info.apply(lambda row: row['RECCAP'] * dic_cur[row['REGCAPCUR']], axis = 1)

In [39]:
company_base_info = company_base_info.drop(["ENTTYPE","INDUSTRYPHY","PARNUM","LIMPARNUM","PARFORM","EXENUM","REGCAP","REGCAPCUR","RECCAP"],axis=1)

In [40]:
company_base_info

,entid,honor_num,illegad_num,yea_sub,web_dum,brand_num,cancel_dum,certificate_num,tax_dum,cap_ratio,...,REGCAPCUR_36.0,REGCAPCUR_156.0,REGCAPCUR_170.0,REGCAPCUR_344.0,REGCAPCUR_392.0,REGCAPCUR_840.0,REGCAPCUR_954.0,REGCAPCUR_978.0,REGCAP_Normal,RECCAP_Normal
0,122697049,0.0,0.0,0.0,1,0.0,0,4.0,0,0.580028,...,0,1,0,0,0,0,0,0,8103057.4,4700000.0
1,959830672,0.0,0.0,0.0,1,0.0,0,2.0,0,0.026316,...,0,1,0,0,0,0,0,0,38000.0,1000.0
2,564421968,0.0,0.0,0.0,0,0.0,1,0.0,0,1.000000,...,0,1,0,0,0,0,0,0,5000.0,5000.0
3,620868429,0.0,0.0,0.0,0,0.0,0,0.0,0,1.000000,...,0,1,0,0,0,0,0,0,10000.0,10000.0
4,1176966297,0.0,0.0,0.0,0,0.0,0,0.0,0,1.000000,...,0,1,0,0,0,0,0,0,3000.0,3000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12274,208371641,0.0,0.0,0.0,0,0.0,0,0.0,0,0.000000,...,0,1,0,0,0,0,0,0,20.0,0.0
12275,331374714,0.0,0.0,0.0,0,0.0,0,0.0,0,0.000000,...,0,1,0,0,0,0,0,0,0.0,0.0
12276,470500045,0.0,0.0,0.0,0,0.0,0,0.0,0,1.000000,...,0,1,0,0,0,0,0,0,50.0,500.0
12277,771018416,0.0,0.0,0.0,0,0.0,0,0.0,0,0.000000,...,0,1,0,0,0,0,0,0,0.0,0.0
12278,1091303326,0.0,0.0,0.0,1,0.0,0,0.0,0,0.000000,...,0,1,0,0,0,0,0,0,0.0,0.0

In [41]:
company_base_info.to_csv(outpath+"company_base_info_processed.csv",index=False)